using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using Nemuri.Inventory;
using Nemuri.Scenes;

namespace Nemuri.UI
{
    public class VisionPuzzleUI : MonoBehaviour
    {
        public static VisionPuzzleUI Instance { get; private set; }

        [Header("Sprites")]
        [SerializeField] private Sprite _slotsSprite;
        [SerializeField] private Sprite _fullSprite;

        private GameObject _overlayPanel;
        private Image _visionBoardImage;
        private Button _unlockButton;
        private Button _closeButton;

        private class PlacedItemInfo
        {
            public int itemId;
            public int originalHotbarIndex;
            public GameObject visualGo;
            public Vector2 localPos;
        }

        private readonly List<PlacedItemInfo> _placedItems = new List<PlacedItemInfo>();

        [Header("Target Coordinates - Group 1 (Circadian Isle)")]
        [SerializeField] private Vector2 _g1Target1 = new Vector2(845f, -259f);  // Clock
        [SerializeField] private Vector2 _g1Target2 = new Vector2(-595f, -86f);  // Lamp
        [SerializeField] private Vector2 _g1Target3 = new Vector2(-883f, -313f); // Files

        [Header("Target Coordinates - Group 2 (Memory Archives)")]
        [SerializeField] private Vector2 _g2Target1 = new Vector2(845f, -259f);  // Photo
        [SerializeField] private Vector2 _g2Target2 = new Vector2(-595f, -86f);  // Novel
        [SerializeField] private Vector2 _g2Target3 = new Vector2(-883f, -313f); // Cassette

        [Header("Target Coordinates - Group 3 (Anxiety Heights)")]
        [SerializeField] private Vector2 _g3Target1 = new Vector2(845f, -259f);  // Coffee
        [SerializeField] private Vector2 _g3Target2 = new Vector2(-595f, -86f);  // Rabbit
        [SerializeField] private Vector2 _g3Target3 = new Vector2(-883f, -313f); // Pills

        private const float MatchTolerance = 120f; // maximum distance deviation in board coordinates

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
            
            InitializeUI();
        }

        private void InitializeUI()
        {
            if (EventSystem.current == null)
            {
                Debug.Log("[VisionPuzzleUI] No EventSystem detected in scene. Creating EventSystem and InputSystemUIInputModule dynamically...");
                GameObject esObj = new GameObject("EventSystem_AutoGenerated");
                esObj.AddComponent<EventSystem>();
                esObj.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
                DontDestroyOnLoad(esObj);
            }

            GameObject canvasObj = GameObject.Find("Vision Puzzle Canvas");
            if (canvasObj == null)
            {
                canvasObj = new GameObject("Vision Puzzle Canvas");
                Canvas canvas = canvasObj.AddComponent<Canvas>();
                canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                canvas.sortingOrder = 1000; // on top of Dialogue Canvas (900)

                CanvasScaler scaler = canvasObj.AddComponent<CanvasScaler>();
                scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
                scaler.referenceResolution = new Vector2(1920f, 1080f);

                canvasObj.AddComponent<GraphicRaycaster>();
                DontDestroyOnLoad(canvasObj);
            }

            // overlay backdrop
            _overlayPanel = new GameObject("PuzzleOverlayPanel");
            _overlayPanel.transform.SetParent(canvasObj.transform, false);
            Image bg = _overlayPanel.AddComponent<Image>();
            bg.color = new Color(0f, 0f, 0f, 0.85f);

            RectTransform bgRect = _overlayPanel.GetComponent<RectTransform>();
            bgRect.anchorMin = Vector2.zero;
            bgRect.anchorMax = Vector2.one;
            bgRect.offsetMin = Vector2.zero;
            bgRect.offsetMax = Vector2.zero;

            // vision board image (size 1920x1080, centered)
            GameObject boardObj = new GameObject("VisionBoard");
            boardObj.transform.SetParent(_overlayPanel.transform, false);
            _visionBoardImage = boardObj.AddComponent<Image>();
            _visionBoardImage.color = Color.black; 
            _visionBoardImage.raycastTarget = true; // MUST receive drop events

            // Add drop handler proxy
            boardObj.AddComponent<VisionPuzzleBoardDropZone>();
            
            // load sprite assets: slots.PNG has question marks (puzzle state), full.PNG is completed
#if UNITY_EDITOR
            if (_slotsSprite == null) _slotsSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Maps/CHAPT2/slots.PNG");
            if (_fullSprite == null) _fullSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Maps/CHAPT2/full.PNG");
#endif
            if (_slotsSprite == null) _slotsSprite = Resources.Load<Sprite>("slots");
            if (_fullSprite == null) _fullSprite = Resources.Load<Sprite>("full");

            if (_slotsSprite != null)
            {
                _visionBoardImage.sprite = _slotsSprite;
                _visionBoardImage.color = Color.white;
            }

            RectTransform boardRect = _visionBoardImage.GetComponent<RectTransform>();
            boardRect.anchorMin = Vector2.zero;
            boardRect.anchorMax = Vector2.one;
            boardRect.pivot = new Vector2(0.5f, 0.5f);
            boardRect.offsetMin = Vector2.zero;
            boardRect.offsetMax = Vector2.zero;
            boardRect.localScale = Vector3.one;

            // unlock button at top center of board (so it's never covered by the hotbar)
            GameObject unlockGo = new GameObject("UnlockButton");
            unlockGo.transform.SetParent(_visionBoardImage.transform, false);
            _unlockButton = unlockGo.AddComponent<Button>();
            Image btnImg = unlockGo.AddComponent<Image>();
            btnImg.color = new Color(0.18f, 0.54f, 0.34f, 1f); // forest green

            RectTransform btnRect = unlockGo.GetComponent<RectTransform>();
            btnRect.anchorMin = new Vector2(0.5f, 1f);
            btnRect.anchorMax = new Vector2(0.5f, 1f);
            btnRect.pivot = new Vector2(0.5f, 0.5f);
            btnRect.anchoredPosition = new Vector2(0f, -60f); // 60 units below top edge
            btnRect.sizeDelta = new Vector2(180f, 50f);

            GameObject textGo = new GameObject("Text");
            textGo.transform.SetParent(unlockGo.transform, false);
            Text btnTxt = textGo.AddComponent<Text>();
            btnTxt.text = "UNLOCK";
            btnTxt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            btnTxt.fontSize = 24;
            btnTxt.alignment = TextAnchor.MiddleCenter;
            btnTxt.color = Color.white;

            RectTransform txtRect = btnTxt.rectTransform;
            txtRect.anchorMin = Vector2.zero;
            txtRect.anchorMax = Vector2.one;
            txtRect.offsetMin = Vector2.zero;
            txtRect.offsetMax = Vector2.zero;

            _unlockButton.onClick.AddListener(OnUnlockPressed);

            // close button X (top right)
            GameObject closeGo = new GameObject("CloseButton");
            closeGo.transform.SetParent(_overlayPanel.transform, false);
            _closeButton = closeGo.AddComponent<Button>();
            Image closeImg = closeGo.AddComponent<Image>();
            closeImg.color = new Color(0.7f, 0.15f, 0.15f, 1f); // dark red

            RectTransform closeRect = closeGo.GetComponent<RectTransform>();
            closeRect.anchorMin = new Vector2(0.95f, 0.95f);
            closeRect.anchorMax = new Vector2(0.95f, 0.95f);
            closeRect.pivot = new Vector2(0.5f, 0.5f);
            closeRect.sizeDelta = new Vector2(50f, 50f);

            GameObject closeTxtGo = new GameObject("Text");
            closeTxtGo.transform.SetParent(closeGo.transform, false);
            Text closeTxt = closeTxtGo.AddComponent<Text>();
            closeTxt.text = "X";
            closeTxt.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            closeTxt.fontSize = 28;
            closeTxt.alignment = TextAnchor.MiddleCenter;
            closeTxt.color = Color.white;

            RectTransform closeTxtRect = closeTxt.rectTransform;
            closeTxtRect.anchorMin = Vector2.zero;
            closeTxtRect.anchorMax = Vector2.one;
            closeTxtRect.offsetMin = Vector2.zero;
            closeTxtRect.offsetMax = Vector2.zero;

            _closeButton.onClick.AddListener(OnClosePressed);

            _overlayPanel.SetActive(false);
        }

        public void SetVisible(bool visible)
        {
            if (_overlayPanel != null)
            {
                _overlayPanel.SetActive(visible);
            }

            if (visible)
            {
                ResetPuzzle();
                LoadTexturesForActiveGroup();

                if (_slotsSprite != null && _visionBoardImage != null)
                {
                    _visionBoardImage.sprite = _slotsSprite;
                    _visionBoardImage.color = Color.white;
                }
            }
        }

        private void LoadTexturesForActiveGroup()
        {
            ItemGroup activeGroup = HippocampusIntroController.Instance != null ? HippocampusIntroController.Instance.CurrentActiveGroup : ItemGroup.Group1;
            string slotsPath = "Assets/Maps/CHAPT2/slots.PNG";
            string fullPath = "Assets/Maps/CHAPT2/full.PNG";
            string resSlots = "slots";
            string resFull = "full";

            if (activeGroup == ItemGroup.Group2)
            {
                slotsPath = "Assets/Maps/CHAPT2/slots2.PNG";
                fullPath = "Assets/Maps/CHAPT2/full2.PNG";
                resSlots = "slots2";
                resFull = "full2";
            }
            else if (activeGroup == ItemGroup.Group3)
            {
                slotsPath = "Assets/Maps/CHAPT2/slots3.PNG";
                fullPath = "Assets/Maps/CHAPT2/full3.PNG";
                resSlots = "slots3";
                resFull = "full3";
            }

#if UNITY_EDITOR
            _slotsSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>(slotsPath);
            _fullSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>(fullPath);
#endif
            if (_slotsSprite == null) _slotsSprite = Resources.Load<Sprite>(resSlots);
            if (_fullSprite == null) _fullSprite = Resources.Load<Sprite>(resFull);

            // Fallback to Group 1 textures if Group 2/3 textures don't exist yet
            if (_slotsSprite == null)
            {
#if UNITY_EDITOR
                _slotsSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Maps/CHAPT2/slots.PNG");
#endif
                if (_slotsSprite == null) _slotsSprite = Resources.Load<Sprite>("slots");
            }
            if (_fullSprite == null)
            {
#if UNITY_EDITOR
                _fullSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/Maps/CHAPT2/full.PNG");
#endif
                if (_fullSprite == null) _fullSprite = Resources.Load<Sprite>("full");
            }

            Vector2 target1 = _g1Target1;
            Vector2 target2 = _g1Target2;
            Vector2 target3 = _g1Target3;

            if (activeGroup == ItemGroup.Group2)
            {
                target1 = _g2Target1;
                target2 = _g2Target2;
                target3 = _g2Target3;
            }
            else if (activeGroup == ItemGroup.Group3)
            {
                target1 = _g3Target1;
                target2 = _g3Target2;
                target3 = _g3Target3;
            }

            Debug.Log(string.Format("[VisionPuzzleUI] Opened Puzzle for {0}. Expected asset paths: Slots='{1}', Full='{2}'. Targets: Item1={3}, Item2={4}, Item3={5}",
                activeGroup,
                slotsPath,
                fullPath,
                target1,
                target2,
                target3));
        }

        public void OnItemDroppedOnBoard(PointerEventData eventData)
        {
            if (HotbarSlotDragHandler.DraggedSlot == null) return;

            HotbarSlotDragHandler dragHandler = HotbarSlotDragHandler.DraggedSlot;
            HotbarItem item = dragHandler.Item;
            if (item == null) return;

            // Remove any existing placement for this item ID (replace/update position)
            PlacedItemInfo toRemove = null;
            foreach (var placed in _placedItems)
            {
                if (placed.itemId == item.itemId)
                {
                    toRemove = placed;
                    break;
                }
            }

            if (toRemove != null)
            {
                RestoreHotbarSlotIcon(toRemove.originalHotbarIndex);
                if (toRemove.visualGo != null) Destroy(toRemove.visualGo);
                _placedItems.Remove(toRemove);
            }

            // Convert position to local board coordinates
            RectTransform boardRect = _visionBoardImage.GetComponent<RectTransform>();
            Vector2 localPoint;
            RectTransformUtility.ScreenPointToLocalPointInRectangle(
                boardRect,
                eventData.position,
                eventData.pressEventCamera,
                out localPoint
            );

            // Create image clone on the board
            GameObject cloneObj = new GameObject("Dropped_" + item.displayName);
            cloneObj.transform.SetParent(_visionBoardImage.transform, false);

            Image img = cloneObj.AddComponent<Image>();
            img.sprite = item.icon;
            img.raycastTarget = true; // MUST be true to receive drag events again

            RectTransform rt = cloneObj.GetComponent<RectTransform>();
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = localPoint;
            rt.sizeDelta = new Vector2(100f, 100f);

            // Attach drag handler to let player drag it again on the board
            DroppedPuzzleItemDragHandler boardDrag = cloneObj.AddComponent<DroppedPuzzleItemDragHandler>();
            boardDrag.Initialize(item.itemId, boardRect);

            // Record placement
            _placedItems.Add(new PlacedItemInfo
            {
                itemId = item.itemId,
                originalHotbarIndex = dragHandler.SlotIndex,
                visualGo = cloneObj,
                localPos = localPoint
            });

            Debug.Log(string.Format("[VisionPuzzleUI] Placed {0} at board coords {1}. DragHandler attached.", item.displayName, localPoint));

            dragHandler.OnPlacedInPuzzle();
        }

        public bool IsItemPlacedInPuzzle(int hotbarIndex)
        {
            foreach (var placed in _placedItems)
            {
                if (placed.originalHotbarIndex == hotbarIndex)
                {
                    return true;
                }
            }
            return false;
        }

        public void HideHotbarSlotIcon(int index)
        {
            HotbarUI ui = FindAnyObjectByType<HotbarUI>();
            if (ui != null)
            {
                ui.SetSlotIconVisible(index, false);
            }
        }

        public void RestoreHotbarSlotIcon(int index)
        {
            HotbarUI ui = FindAnyObjectByType<HotbarUI>();
            if (ui != null)
            {
                ui.SetSlotIconVisible(index, true);
            }
        }

        private void ResetPuzzle()
        {
            foreach (var placed in _placedItems)
            {
                RestoreHotbarSlotIcon(placed.originalHotbarIndex);
                if (placed.visualGo != null)
                {
                    Destroy(placed.visualGo);
                }
            }
            _placedItems.Clear();
        }

        private void OnUnlockPressed()
        {
            Debug.Log("[VisionPuzzleUI] UNLOCK button pressed!");
            
            ItemGroup activeGroup = HippocampusIntroController.Instance != null ? HippocampusIntroController.Instance.CurrentActiveGroup : ItemGroup.Group1;
            int baseId = (int)activeGroup * 3; // Group1: 0, Group2: 3, Group3: 6

            Vector2 target1 = _g1Target1;
            Vector2 target2 = _g1Target2;
            Vector2 target3 = _g1Target3;

            if (activeGroup == ItemGroup.Group2)
            {
                target1 = _g2Target1;
                target2 = _g2Target2;
                target3 = _g2Target3;
            }
            else if (activeGroup == ItemGroup.Group3)
            {
                target1 = _g3Target1;
                target2 = _g3Target2;
                target3 = _g3Target3;
            }

            PlacedItemInfo item1 = FindPlacedItem(baseId + 1);
            PlacedItemInfo item2 = FindPlacedItem(baseId + 2);
            PlacedItemInfo item3 = FindPlacedItem(baseId + 3);

            bool item1Correct = item1 != null && Vector2.Distance(item1.localPos, target1) <= MatchTolerance;
            bool item2Correct = item2 != null && Vector2.Distance(item2.localPos, target2) <= MatchTolerance;
            bool item3Correct = item3 != null && Vector2.Distance(item3.localPos, target3) <= MatchTolerance;

            Debug.Log(string.Format("[VisionPuzzleUI] Verification ({0}) - Item1: {1} (dist: {2}), Item2: {3} (dist: {4}), Item3: {5} (dist: {6})",
                activeGroup,
                item1Correct, item1 != null ? Vector2.Distance(item1.localPos, target1).ToString("F1") : "Missing",
                item2Correct, item2 != null ? Vector2.Distance(item2.localPos, target2).ToString("F1") : "Missing",
                item3Correct, item3 != null ? Vector2.Distance(item3.localPos, target3).ToString("F1") : "Missing"));

            if (item1Correct && item2Correct && item3Correct)
            {
                Debug.Log("[VisionPuzzleUI] UNLOCK SUCCESS - Memory reconstructed!");
                if (_fullSprite != null)
                {
                    _visionBoardImage.sprite = _fullSprite;
                }

                // Restore all hotbar slot icons (since items are kept in inventory rather than consumed)
                foreach (var placed in _placedItems)
                {
                    RestoreHotbarSlotIcon(placed.originalHotbarIndex);
                    if (placed.visualGo != null) placed.visualGo.SetActive(false);
                }
                
                if (VisionPuzzleManager.Instance != null)
                {
                    VisionPuzzleManager.Instance.OnPuzzleCompleted();
                }
            }
            else
            {
                Debug.Log("[VisionPuzzleUI] UNLOCK FAILED - Returning incorrect placements.");
                // return WRONG items to hotbar
                List<PlacedItemInfo> toRemove = new List<PlacedItemInfo>();
                
                if (item1 != null && !item1Correct) toRemove.Add(item1);
                if (item2 != null && !item2Correct) toRemove.Add(item2);
                if (item3 != null && !item3Correct) toRemove.Add(item3);

                foreach (var item in toRemove)
                {
                    RestoreHotbarSlotIcon(item.originalHotbarIndex);
                    if (item.visualGo != null) Destroy(item.visualGo);
                    _placedItems.Remove(item);
                }
            }
        }

        private PlacedItemInfo FindPlacedItem(int itemId)
        {
            foreach (var placed in _placedItems)
            {
                if (placed.itemId == itemId) return placed;
            }
            return null;
        }

        private void OnClosePressed()
        {
            Debug.Log("[VisionPuzzleUI] Close button (X) pressed!");
            if (VisionPuzzleManager.Instance != null)
            {
                VisionPuzzleManager.Instance.ClosePuzzle();
            }
        }

        public void UpdatePlacedItemPosition(int itemId, Vector2 newPos)
        {
            foreach (var placed in _placedItems)
            {
                if (placed.itemId == itemId)
                {
                    placed.localPos = newPos;
                    Debug.Log(string.Format("[VisionPuzzleUI] Updated item {0} position on board to {1}", itemId, newPos));
                    break;
                }
            }
        }

        private void Update()
        {
            if (UnityEngine.InputSystem.Pointer.current != null && UnityEngine.InputSystem.Pointer.current.press.wasPressedThisFrame)
            {
                if (EventSystem.current == null)
                {
                    Debug.LogError("[VisionPuzzleUI] EventSystem.current is NULL! UI interactions will NOT work.");
                }
                else
                {
                    var pointerData = new PointerEventData(EventSystem.current) { position = UnityEngine.InputSystem.Pointer.current.position.ReadValue() };
                    var results = new List<RaycastResult>();
                    EventSystem.current.RaycastAll(pointerData, results);
                    Debug.Log("[VisionPuzzleUI] Diagnostic Click - Position: " + pointerData.position + " | Hits count: " + results.Count);
                    for (int i = 0; i < results.Count; i++)
                    {
                        Canvas parentCanvas = results[i].gameObject.GetComponentInParent<Canvas>();
                        Debug.Log(string.Format("  Hit [{0}]: {1} (Canvas sortingOrder: {2})", 
                            i, 
                            results[i].gameObject.name,
                            parentCanvas != null ? parentCanvas.sortingOrder.ToString() : "none"));
                    }
                }
            }
        }
    }

    public class VisionPuzzleBoardDropZone : MonoBehaviour, IDropHandler
    {
        public void OnDrop(PointerEventData eventData)
        {
            if (VisionPuzzleUI.Instance != null)
            {
                VisionPuzzleUI.Instance.OnItemDroppedOnBoard(eventData);
            }
        }
    }
}
